### PR TITLE
Update broken example and refactor documentation and taskfile

### PR DESCRIPTION
**Pull request by RothAndrew**
## what
* Update .gitignore with the more complete version of Terraform ignores
* Update .tool-versions with latest versions of tools
* Update README to more clearly explain how to run the example
* Update file permission on the generated kubeconfig due to a warning in the new version of helm
* Refactor Taskfile, remove unused tasks, and add taskfile with plan, apply, destroy in the examples folder
* Specify version of template terraform provider
* Update version of subnets module in example to 0.31.0 which ignores tfsec warnings
* Update version of rke provider to latest
* Switch to new incubator helm repo since the old one is now deprecated

## why
* Make the example work properly and make it easier to figure out how to use it

## references
* https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/105

### CODE REVIEW

**Review by Xerralt — APPROVED** [review]

**Review by ac-miller — APPROVED** [review]

**Comment by RothAndrew** [comment]
~~Codacy status passed. Not sure why it isn't updating on the PR here...~~ Edit: There it goes

**Comment by RothAndrew** [comment]
Approving on behalf of compliance team (which is just me right now)

**Pull request merged**
