### PR TITLE
Improve naming convention for EC2 instances

### PR DESCRIPTION
**Pull request by RothAndrew**
## what/why

- Improve naming conventions for EC2 instances that get created so it is easier to differentiate the different types of servers

### CODE REVIEW

**Comment by Xerralt** [comment]
LGTM. Should we be concerned about the Bridgecrew alerts?

**Review by Xerralt — APPROVED** [review]

**Comment by RothAndrew** [comment]
> LGTM. Should we be concerned about the Bridgecrew alerts?

I had to disable the Bridgecrew app since it wouldn't let other people log into the system. I'd like to add https://github.com/bridgecrewio/checkov to the pipeline to catch the same stuff later.

As far as the actual findings:

1. EC2 instance should not have public IP - This is already noted in the README. It is almost certainly possible to do the cluster with private IPs only but it wasn't the path of least resistance so it wasn't done in the MVP.
2. Ensure Instance Metadata Service Version 1 is not enabled - Something we can look at fixing, but not a critical issue
3. Ensure all data stored in the Launch configuration EBS is securely encrypted - Something that we can look at adding, but not a critical issue since this module is meant to be used in an ephemeral environment.

**Pull request merged**
